[build]
  publish = "."
  command = "echo 'Static site ready'"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "nft"

[[redirects]]
  from = "/pdf"
  to = "/pdf.html"
  status = 200

[[headers]]
  for = "/js/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"